[package]
name = "rust-gecko"
version = "0.1.0"
authors = ["Chao Ma <mc8305@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.2"
clap = "2.33.2"
surf = "1.0.3"
